# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 13:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('year_level', models.CharField(max_length=7, validators=[django.core.validators.int_list_validator])),
            ],
        ),
    ]
